alias: Humidity_Fenster_closetoopen
description: ''
trigger:
  - platform: state
    entity_id: sensor.fenster_1
    from: closed
    to: open
condition: []
action:
  - service: automation.turn_off
    target:
      entity_id: automation.humidity_managementv2
mode: single
