## Automatisierung
alias: Wake-up light alarm with sunrise effect justin demo
description: ''
use_blueprint:
  path: sbyx/wake-up-light-alarm-with-sunrise-effect.yaml
  input:
    light_entity: light.tybf30886f2fff0d4799zxvf
    check_entity: automation.weekend_sunrise
    manual_time: '13:41:00'
    pre_sunrise_actions:
      - service: notify.mobile_app_iphone_von_karsten
        data:
          message: Justin muss aufstehen
          data:
            actions:
              - action: SLEEP
                title: Sleep
              - action: WACH
                title: Ich bin wach
    sunrise_duration: 5
    timestamp_sensor: input_datetime.justin_aufstehen_schule
    
    
    
alias: Turn on the lights from actionable notification.
trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: TURN_ON_LIGHTS
action:
  - service: switch.turn_on
    target:
      entity_id: switch.tp_link_01
  - service: script.justin_sleep_modus
mode: single


alias: Weekday Sunrise
description: ''
trigger:
  - platform: time_pattern
    minutes: /1
condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: input_boolean.weekday_sunrise
    state: 'on'
  - condition: template
    value_template: >-
      {{ ((as_timestamp(now())|int)|timestamp_custom("%H:%M"))  ==
      states("sensor.weekday_alarm_time") }}
action:
  - service: media_player.play_media
    data:
      media_content_id: >-
        https://kt-montage.com/files/Elton_John_-_Circle_of_Life_From_The_Lion_King_Official_Video.mp3
      media_content_type: audio/mp3
    target:
      entity_id: media_player.nathalies_echo_dot
  - delay: 3
  - service: script.turn_on
    target:
      entity_id: script.sunrise
mode: single

alias: Weekend Sunrise
description: ''
trigger:
  - platform: time_pattern
    minutes: /1
condition:
  - condition: time
    weekday:
      - sat
      - sun
  - condition: state
    entity_id: input_boolean.weekend_sunrise
    state: 'on'
  - condition: template
    value_template: >-
      {{ ((as_timestamp(now())|int)|timestamp_custom("%H:%M"))  ==
      states("sensor.weekend_alarm_time") }}
action:
  - service: script.turn_on
    target:
      entity_id: script.sunrise
mode: single

    
    
## Script
alias: justin_sleep_modus
sequence:
  - type: turn_on
    device_id: 29df9aaf2c8d42c5d2afbcc480110d84
    entity_id: light.extended_color_light_2
    domain: light
    brightness_pct: 50
mode: single


alias: justin_wach_modus
sequence:
  - repeat:
      count: '2'
      sequence:
        - delay:
            hours: 0
            minutes: 5
            seconds: 0
            milliseconds: 0
  - type: turn_on
    device_id: 76be9583bde6efb0455eb6df681d4b84
    entity_id: light.tybf30886f2fff0d4799zxvf
    domain: light
    brightness_pct: 50
mode: single


## Input _ Helfer

input_datetime.justin_aufstehen_schule

input_boolean.weekday_sunrise

input_boolean.weekend_sunrise

## Lovelace Karte
type: custom:hui-entities-card
entities:
  - type: custom:banner-card
    heading: Aufstehen
    entities:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            entity: switch.test
            lock:
              enabled: true
          - type: custom:button-card
            color_type: card
            lock:
              enabled: true
            color: black
            entity: switch.test
  - card:
      entity: automation.weekend_sunrise
      name: Wecker An/Aus
    restrictions:
      pin:
        code: 1234
    type: custom:restriction-card
    row: true
  - card:
      entity: input_datetime.justin_aufstehen_schule
      name: Aufstehen Schule
    restrictions:
      pin:
        code: 1234
    type: custom:restriction-card
    row: true
  - card:
      entity: input_datetime.bettzeit_justin
    restrictions:
      pin:
        code: 1234
    type: custom:restriction-card
    row: true
