#automation
alias: Weekday Sunrise
description: ''
trigger:
  - platform: time_pattern
    minutes: /1
condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: input_boolean.weekday_sunrise
    state: 'on'
  - condition: template
    value_template: >-
      {{ ((as_timestamp(now())|int)|timestamp_custom("%H:%M"))  ==
      states("sensor.weekday_alarm_time") }}
action:
  - service: media_player.play_media
    data:
      media_content_id: >-
        https://kt-montage.com/files/Elton_John_-_Circle_of_Life_From_The_Lion_King_Official_Video.mp3
      media_content_type: audio/mp3
    target:
      entity_id: media_player.nathalies_echo_dot
  - delay: 3
  - service: script.turn_on
    target:
      entity_id: script.sunrise
mode: single
