#automation
alias: Weekend Sunrise
description: ''
trigger:
  - platform: time_pattern
    minutes: /1
condition:
  - condition: time
    weekday:
      - sat
      - sun
  - condition: state
    entity_id: input_boolean.weekend_sunrise
    state: 'on'
  - condition: template
    value_template: >-
      {{ ((as_timestamp(now())|int)|timestamp_custom("%H:%M"))  ==
      states("sensor.weekend_alarm_time") }}
action:
  - service: script.turn_on
    target:
      entity_id: script.sunrise
mode: single
