blueprint:
  name: Lichtwecker mit Sonnenaufgangseffekt
  description: 'Ein Lichtwecker mit einem Sonnenaufgang in Helligkeit und Farbtemperatur
    Note: Benötigt date_time_iso Sensor in Konfiguration, nicht manuell ausführbar!!'
  domain: automation
  input:
    light_entity:
      name: Aufwach-Licht-Entität
      description: Wähle hier die Entität aus, wo der Lichtwecker mit Sonnenaufgangseffekt ausgeführt werden soll.
      selector:
        entity:
          domain: light
    timestamp_sensor:
      name: Alarm timestamp sensor
      description: 'Sensor mit Zeitstempel des nächsten Alarms mit Geräteklasse(device_class): Zeitstempel / timestamp
        (für manuelle Weckzeit auf ''none'' setzen)'
      default: none
      selector:
        entity:
          device_class: timestamp
    manual_time:
      name: Manuelle Weckzeit
      description: Zeit zum täglichen Auslösen des Alarms, wenn der Zeitstempelsensor nicht eingestellt ist.
        Einstellungen um oder kurz nach Mitternacht funktionieren nicht wie erwartet!!
      default: '7:00:00'
      selector:
        time: {}
    check_entity:
      name: Zusätzliche zu prüfende Entität, bevor Sonnenaufgang ausgelöst wird
      description: Wenn gesetzt, prüft vor dem Auslösen, ob die Entität 'an' oder 'home' ist.
        Benutze z.B. ein (Arbeitstags-)Sensor, einen device_tracker oder eine Personenentität.
      default: none
      selector:
        entity: {}
    sunrise_duration:
      name: Dauer des Sonnenaufgangs
      description: Der Sonnenaufgang beginnt die konfigurierte Anzahl von Minuten vorher dem Zeitstempel
      default: 25
      selector:
        number:
          min: 5.0
          max: 60.0
          step: 5.0
          unit_of_measurement: min
          mode: slider
    start_brightness:
      name: Minimum brightness
      description: Die Helligkeit zu Beginn. 
        Einige Lichter ignorieren sehr niedrige Werte und könnten stattdessen mit voller Helligkeit einschalten!
      default: 1
      selector:
        number:
          min: 1.0
          max: 255.0
          step: 1.0
          mode: slider
    end_brightness:
      name: Maximum brightness
      description: Die Helligkeit wird vom Minimum auf den konfigurierten Wert geändert.
      default: 254
      selector:
        number:
          min: 5.0
          max: 255.0
          step: 1.0
          mode: slider
    min_mired:
      name: Minimum color temperature
      description: 'Die minimal zu verwendende Farbtemperatur. (0: niedrigster unterstützter Wert)'
      default: 0
      selector:
        number:
          min: 0.0
          max: 500.0
          step: 5.0
          mode: slider
          unit_of_measurement: mired
    pre_sunrise_actions:
      name: Aktionen vor Sonnenaufgang
      description: Optionale Aktionen, die vor Sonnenaufgang ausgeführt werden sollen.
      default: []
      selector:
        action: {}
    post_sunrise_actions:
      name: Aktionen nach Sonnenaufgang
      description: Optionale Aktionen, die nach dem Ende des Sonnenaufgangs (um die Weckzeit herum) ausgeführt werden sollen.
      default: []
      selector:
        action: {}
  source_url: https://gist.github.com/loremipsum
variables:
  light_entity: !input 'light_entity'
  sensor: !input 'timestamp_sensor'
  sunrise_duration: !input 'sunrise_duration'
  start_brightness: !input 'start_brightness'
  end_brightness: !input 'end_brightness'
  range_brightness: '{{float(end_brightness)-float(start_brightness)}}'
  manual_time: !input 'manual_time'
  seconds: '{{float(sunrise_duration) * 60}}'
  min_mired: !input 'min_mired'
  start_mired: '{{state_attr(light_entity, ''max_mireds'')}}'
  end_mired: '{{[state_attr(light_entity, ''min_mireds'')|int(0), min_mired|int(0)]|max}}'
  tick_time: '{{float(seconds) / float(range_brightness)}}'
  check_entity: !input 'check_entity'
trigger:
- platform: time_pattern
  minutes: '*'
condition: []
action:
- wait_template: '{{sensor == ''none'' or as_timestamp(states(sensor), None) != None}}'
- wait_template: '{{0 < as_timestamp(states(sensor) if sensor != ''none'' else states(''sensor.date'')
    ~ '' '' ~ manual_time) - as_timestamp(states(''sensor.date_time_iso'')) <= float(seconds)
    and states(check_entity) in [''unknown'', ''on'', ''home'']}}'
- choose: []
  default: !input 'pre_sunrise_actions'
- condition: template
  value_template: '{{sensor == ''none'' or as_timestamp(states(sensor), None) != None}}'
- condition: template
  value_template: '{{0 < as_timestamp(states(sensor) if sensor != ''none'' else states(''sensor.date'')
    ~ '' '' ~ manual_time) - as_timestamp(now()) <= float(seconds) and states(check_entity)
    in [''unknown'', ''on'', ''home'']}}'
- choose:
  - conditions:
    - '{{state_attr(light_entity, ''min_mireds'') != None}}'
    sequence:
    - service: light.turn_on
      data:
        brightness: '{{start_brightness}}'
        color_temp: '{{start_mired}}'
      entity_id: !input 'light_entity'
  default:
  - service: light.turn_on
    data:
      brightness: '{{start_brightness}}'
    entity_id: !input 'light_entity'
- repeat:
    while:
    - '{{sensor == ''none'' or as_timestamp(states(sensor), None) != None}}'
    - '{{0 < as_timestamp(states(sensor) if sensor != ''none'' else states(''sensor.date'')
      ~ '' '' ~ manual_time) - as_timestamp(now()) <= float(seconds)}}'
    sequence:
    - delay: '{{tick_time}}'
    - choose:
      - conditions:
        - '{{0 < state_attr(light_entity, ''brightness'') | int(0) < end_brightness |
          int}}'
        - '{{sensor == ''none'' or as_timestamp(states(sensor), None) != None}}'
        - '{{0 < as_timestamp(states(sensor) if sensor != ''none'' else states(''sensor.date'')
          ~ '' '' ~ manual_time) - as_timestamp(now()) <= float(seconds)}}'
        sequence:
        - choose:
          - conditions:
            - '{{state_attr(light_entity, ''min_mireds'') != None}}'
            sequence:
            - service: light.turn_on
              data:
                brightness: '{{(float(end_brightness) - (float(range_brightness) *
                  (as_timestamp(states(sensor) if sensor != ''none'' else states(''sensor.date'')
                  ~ '' '' ~ manual_time) - as_timestamp(now())) / float(seconds)))
                  | int(0)}}'
                color_temp: '{{(float(end_mired) + (float(start_mired) - float(end_mired))
                  * ((as_timestamp(states(sensor) if sensor != ''none'' else states(''sensor.date'')
                  ~ '' '' ~ manual_time) - as_timestamp(now())) / float(seconds)))
                  | int(0)}}'
              entity_id: !input 'light_entity'
          default:
          - service: light.turn_on
            data:
              brightness: '{{(float(end_brightness) - (float(range_brightness) * (as_timestamp(states(sensor)
                if sensor != ''none'' else states(''sensor.date'') ~ '' '' ~ manual_time)
                - as_timestamp(now())) / float(seconds))) | int(0)}}'
            entity_id: !input 'light_entity'
- choose: []
  default: !input 'post_sunrise_actions'
mode: single
max_exceeded: silent
